spring:
  profile: test
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:~/test
    username: sa
    h2:
      console:
        enabled: true
        path: /h2
    jpa:
      hibernate:
        ddl-auto: update
      database-platform:
        org.hibernate.dialect.H2Dialect